// Command prism-sync copies canonical templates and rubrics from
// github.com/grokify/prism-roadmap into this library's workflow directories.
//
// prism-roadmap is the domain home (source of truth) for roadmap-related spec
// content: canvas documents (opportunity-spec, ost, assumption-map,
// discovery-snapshot) and the v2mom goals family. This library embeds copies so
// consumers get a self-contained module with no filesystem or network access;
// prism-sync makes the copy step reproducible and stamps each file with its
// provenance.
//
// The mapping from source file to destination workflow directories lives in
// manifest.yaml next to this file.
//
// Usage (from the repo root):
//
//	go run -C tools/prism-sync .          # write synced copies
//	go run -C tools/prism-sync . -check   # verify copies match (for CI); no writes
//
// This is a separate Go module so the library's go.mod never depends on
// prism-roadmap.
package main

import (
	_ "embed"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime/debug"

	"github.com/grokify/prism-roadmap/rubrics"
	"github.com/grokify/prism-roadmap/templates"
	"gopkg.in/yaml.v3"
)

//go:embed manifest.yaml
var manifestYAML []byte

const sourceModule = "github.com/grokify/prism-roadmap"

// Manifest maps prism-roadmap source names to destination workflow directories.
type Manifest struct {
	// Templates are markdown template mappings (templates/<name>.md).
	Templates []Mapping `yaml:"templates"`

	// Rubrics are rubric mappings (rubrics/<name>.rubric.yaml).
	Rubrics []Mapping `yaml:"rubrics"`
}

// Mapping is one source file and the workflow directories it lands in.
type Mapping struct {
	// Name is the source name without suffix (e.g., "ost", "v2mom-vision").
	Name string `yaml:"name"`

	// Workflows are destination workflow directory names under
	// pkg/workflows/default/.
	Workflows []string `yaml:"workflows"`
}

func main() {
	check := flag.Bool("check", false, "verify committed copies match the source; write nothing")
	root := flag.String("root", "../..", "repository root (default assumes running via go run -C tools/prism-sync .)")
	flag.Parse()

	if err := run(*root, *check); err != nil {
		fmt.Fprintf(os.Stderr, "prism-sync: %v\n", err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	var m Manifest
	if err := yaml.Unmarshal(manifestYAML, &m); err != nil {
		return fmt.Errorf("parsing manifest: %w", err)
	}

	version := prismVersion()
	var drift []string

	for _, t := range m.Templates {
		content, err := templates.Get(t.Name)
		if err != nil {
			return fmt.Errorf("template %q: %w", t.Name, err)
		}
		header := fmt.Sprintf("<!-- Code generated by prism-sync; DO NOT EDIT.\nSource: %s@%s templates/%s.md -->\n\n", sourceModule, version, t.Name)
		for _, wf := range t.Workflows {
			dest := filepath.Join(root, "pkg", "workflows", "default", wf, "templates", t.Name+".md")
			d, err := syncFile(dest, header+content, check)
			if err != nil {
				return fmt.Errorf("template %q -> %s: %w", t.Name, wf, err)
			}
			if d {
				drift = append(drift, dest)
			}
		}
	}

	for _, r := range m.Rubrics {
		content, err := rubrics.Get(r.Name)
		if err != nil {
			return fmt.Errorf("rubric %q: %w", r.Name, err)
		}
		header := fmt.Sprintf("# Code generated by prism-sync; DO NOT EDIT.\n# Source: %s@%s rubrics/%s.rubric.yaml\n\n", sourceModule, version, r.Name)
		for _, wf := range r.Workflows {
			dest := filepath.Join(root, "pkg", "workflows", "default", wf, "rubrics", r.Name+".rubric.yaml")
			d, err := syncFile(dest, header+content, check)
			if err != nil {
				return fmt.Errorf("rubric %q -> %s: %w", r.Name, wf, err)
			}
			if d {
				drift = append(drift, dest)
			}
		}
	}

	if check {
		if len(drift) > 0 {
			for _, f := range drift {
				fmt.Fprintf(os.Stderr, "prism-sync: drift: %s\n", f)
			}
			return fmt.Errorf("%d file(s) out of sync with %s@%s — run: go run -C tools/prism-sync .", len(drift), sourceModule, version)
		}
		fmt.Println("prism-sync: all synced files match")
	}
	return nil
}

// syncFile writes want to dest, or in check mode reports whether dest differs.
// Returns true when the file drifted (check mode only).
func syncFile(dest, want string, check bool) (bool, error) {
	if check {
		got, err := os.ReadFile(dest)
		if err != nil {
			if os.IsNotExist(err) {
				return true, nil
			}
			return false, err
		}
		return !equalIgnoringVersion(string(got), want), nil
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0o750); err != nil {
		return false, err
	}
	if err := os.WriteFile(dest, []byte(want), 0o600); err != nil {
		return false, err
	}
	fmt.Printf("prism-sync: wrote %s\n", dest)
	return false, nil
}

// versionToken matches the @version token in a provenance header line.
var versionToken = regexp.MustCompile(regexp.QuoteMeta(sourceModule) + `@\S+`)

// equalIgnoringVersion compares synced file contents, normalizing the source
// version in the provenance header. Content drift always fails the check;
// a version-only difference (e.g., a local replace resolving to "(devel)")
// does not.
func equalIgnoringVersion(got, want string) bool {
	norm := func(s string) string {
		return versionToken.ReplaceAllString(s, sourceModule+"@VERSION")
	}
	return norm(got) == norm(want)
}

// prismVersion reports the prism-roadmap module version this binary was built
// against, or "(devel)" when built from a local replace.
func prismVersion() string {
	bi, ok := debug.ReadBuildInfo()
	if !ok {
		return "(unknown)"
	}
	for _, dep := range bi.Deps {
		if dep.Path != sourceModule {
			continue
		}
		if dep.Replace != nil {
			return dep.Replace.Version
		}
		return dep.Version
	}
	return "(unknown)"
}
