package speckit

import "fmt"

// generatorName identifies the tool in provenance headers. The committed
// artifacts under speckit/ are regenerated by `visionspec speckit export`;
// hand-edits are overwritten and rejected by the --check drift gate.
const generatorName = "visionspec speckit export"

const sourceModule = "github.com/ProductBuildersHQ/visionspec"

// markdownHeader returns the DO-NOT-EDIT provenance header for generated
// markdown files, following the prism-sync convention.
func markdownHeader(family string) string {
	return fmt.Sprintf("<!-- Code generated by %s; DO NOT EDIT.\nSource: %s pkg/workflows/default/%s -->\n\n",
		generatorName, sourceModule, family)
}

// yamlHeader returns the DO-NOT-EDIT provenance header for generated YAML
// files, following the prism-sync convention.
func yamlHeader(family string) string {
	return fmt.Sprintf("# Code generated by %s; DO NOT EDIT.\n# Source: %s pkg/workflows/default/%s\n\n",
		generatorName, sourceModule, family)
}
