package speckit

import (
	"slices"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/ProductBuildersHQ/visionspec/pkg/workflows"
)

func buildTestWorkflow(t *testing.T) File {
	t.Helper()
	lw, err := workflows.DefaultLoader().Load(testFamily)
	if err != nil {
		t.Fatal(err)
	}
	f, err := BuildWorkflow(lw, Options{})
	if err != nil {
		t.Fatal(err)
	}
	return f
}

func TestBuildWorkflowParsesAndSatisfiesSchema(t *testing.T) {
	f := buildTestWorkflow(t)

	if f.Path != "workflows/one-way-door-chain/workflow.yml" {
		t.Errorf("path = %q", f.Path)
	}

	var m WorkflowManifest
	if err := yaml.Unmarshal(f.Content, &m); err != nil {
		t.Fatalf("workflow.yml does not parse: %v", err)
	}
	if m.SchemaVersion != "1.0" {
		t.Errorf("schema_version = %q, want 1.0", m.SchemaVersion)
	}
	if m.Workflow.ID != "one-way-door-chain" {
		t.Errorf("workflow.id = %q", m.Workflow.ID)
	}
	if m.Requires.SpecKitVersion == "" {
		t.Error("requires.speckit_version is empty")
	}
	if len(m.Steps) == 0 {
		t.Fatal("no steps generated")
	}
	if _, ok := m.Inputs["work"]; !ok {
		t.Error("missing work input")
	}
	if _, ok := m.Inputs["slug"]; !ok {
		t.Error("missing slug input")
	}
}

// stepIDsOf walks the raw YAML (not the typed manifest, since Steps is
// []any and loses concrete shape through yaml.Unmarshal into a generic
// document) collecting every "id" key at any nesting depth, to check
// spec-kit's global step-id-uniqueness constraint.
func stepIDsOf(t *testing.T, content []byte) []string {
	t.Helper()
	var doc yaml.Node
	if err := yaml.Unmarshal(content, &doc); err != nil {
		t.Fatal(err)
	}
	var ids []string
	var walk func(n *yaml.Node)
	walk = func(n *yaml.Node) {
		if n.Kind == yaml.MappingNode {
			for i := 0; i < len(n.Content)-1; i += 2 {
				k, v := n.Content[i], n.Content[i+1]
				if k.Value == "id" && v.Kind == yaml.ScalarNode {
					ids = append(ids, v.Value)
				}
				walk(v)
			}
			return
		}
		for _, c := range n.Content {
			walk(c)
		}
	}
	walk(&doc)
	return ids
}

func TestBuildWorkflowStepIDsAreUnique(t *testing.T) {
	f := buildTestWorkflow(t)
	ids := stepIDsOf(t, f.Content)
	if len(ids) == 0 {
		t.Fatal("no step ids found")
	}
	seen := map[string]bool{}
	for _, id := range ids {
		if seen[id] {
			t.Errorf("duplicate step id %q", id)
		}
		seen[id] = true
	}
}

func TestBuildWorkflowGateIDsMatchReviewGateStepID(t *testing.T) {
	f := buildTestWorkflow(t)
	ids := stepIDsOf(t, f.Content)
	idSet := map[string]bool{}
	for _, id := range ids {
		idSet[id] = true
	}
	// aws-one-way-door declares gates after faq (prfaq_review) and after
	// narrative-6p (decision_meeting, required).
	for _, want := range []string{"prfaq-review", "decision-meeting"} {
		if !idSet[want] {
			t.Errorf("missing gate step id %q (from ReviewGate.StepID())", want)
		}
	}
}

func TestBuildWorkflowOptionalSpecsAreConditional(t *testing.T) {
	f := buildTestWorkflow(t)
	ids := stepIDsOf(t, f.Content)
	has := func(id string) bool {
		return slices.Contains(ids, id)
	}
	// mrd is optional (SpecConfig.Required == false) — it must appear as the
	// if-wrapper id "mrd" plus the nested command id "mrd-run", not as a bare
	// unconditional "mrd" command step.
	if !has("mrd") || !has("mrd-run") {
		t.Error("optional spec mrd is not wrapped in an if step (want ids \"mrd\" and \"mrd-run\")")
	}
	// press and prd are required — plain command steps, id equals the spec.
	if !has("press") || !has("prd") {
		t.Error("required specs press/prd missing from step ids")
	}
}

func TestBuildWorkflowCommandsReferenceCorrectExtension(t *testing.T) {
	f := buildTestWorkflow(t)
	content := string(f.Content)
	for _, want := range []string{
		"speckit.one-way-door.press",
		"speckit.one-way-door.faq",
		"speckit.one-way-door.prd",
		"speckit.one-way-door.narrative-6p",
		"speckit.one-way-door.uxd",
		"speckit.one-way-door-engineering.trd",
		"speckit.one-way-door-engineering.tpd",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("workflow does not reference command %q", want)
		}
	}
}

func TestBuildWorkflowDeterministic(t *testing.T) {
	a := buildTestWorkflow(t)
	b := buildTestWorkflow(t)
	if string(a.Content) != string(b.Content) {
		t.Error("BuildWorkflow output is not deterministic")
	}
}

func TestBuildWorkflowProvenanceHeader(t *testing.T) {
	f := buildTestWorkflow(t)
	if !strings.Contains(string(f.Content), "Code generated by visionspec speckit export; DO NOT EDIT.") {
		t.Error("missing provenance header")
	}
}

func TestBuildWorkflowRejectsInvalidID(t *testing.T) {
	lw, err := workflows.DefaultLoader().Load(testFamily)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := BuildWorkflow(lw, Options{WorkflowID: "Bad_ID"}); err == nil {
		t.Error("invalid workflow id accepted")
	}
}
