// Code generated by tmp_genrubrics; DO NOT EDIT.
// Source: visionspec's original flat rubric definitions, migrated to the
// canonical structured-evaluation rubric.RubricSet (A-literal migration).

package rubrics

import (
	"github.com/ProductBuildersHQ/visionspec/pkg/types"
	"github.com/plexusone/structured-evaluation/rubric"
)

func init() {
	{
		rs := rubric.NewRubricSet("aidlc-architecture-rubric", "AIDLC Architecture Specification Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Architecture Specifications for system design, component interactions, and deployment topology"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("system_design", "System Design", "Overall system architecture and component breakdown").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Clear system decomposition with well-defined boundaries, responsibilities, and interaction patterns"}, []string{"System design exists but component boundaries unclear"}, []string{"No clear system design or architecture"}))
		rs.AddCategory(*rubric.NewCategory("data_architecture", "Data Architecture", "Data flow, storage, and consistency approach").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Data models, storage strategies, consistency requirements, and data flow patterns clearly documented"}, []string{"Some data architecture present but incomplete"}, []string{"Data architecture not addressed"}))
		rs.AddCategory(*rubric.NewCategory("integration_patterns", "Integration Patterns", "API design and service integration approach").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Integration patterns documented with API contracts, protocols, and error handling strategies"}, []string{"Integration approach mentioned but lacks detail"}, []string{"No integration patterns defined"}))
		rs.AddCategory(*rubric.NewCategory("deployment_topology", "Deployment Topology", "Infrastructure and deployment architecture").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Deployment topology clearly documented with infrastructure requirements, networking, and scaling approach"}, []string{"Basic deployment info present but gaps exist"}, []string{"Deployment topology not addressed"}))
		rs.AddCategory(*rubric.NewCategory("diagrams", "Architecture Diagrams", "Visual representations of the architecture").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Clear architecture diagrams (C4, sequence, etc.) that accurately represent the system"}, []string{"Some diagrams present but incomplete or unclear"}, []string{"No architecture diagrams included"}))
		Register(types.SpecType("aidlc-architecture"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-disaster-rubric", "AIDLC Disaster Recovery Plan Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Disaster Recovery Plans for RTO/RPO, backup strategy, and recovery procedures"
		rs.PassCriteria = StrictPassCriteria()
		rs.AddCategory(*rubric.NewCategory("rto_rpo", "RTO/RPO Definition", "Recovery time and point objectives").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"RTO and RPO clearly defined per service tier with business justification"}, []string{"RTO/RPO mentioned but not per service or lacking justification"}, []string{"RTO/RPO not defined"}))
		rs.AddCategory(*rubric.NewCategory("backup_strategy", "Backup Strategy", "Data backup and replication approach").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Backup schedule, retention policy, geographic distribution, and encryption documented"}, []string{"Basic backup info present but incomplete"}, []string{"Backup strategy not documented"}))
		rs.AddCategory(*rubric.NewCategory("recovery_procedures", "Recovery Procedures", "Step-by-step recovery process").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Detailed recovery procedures with verification steps, dependencies, and communication plan"}, []string{"Recovery procedures exist but lack detail"}, []string{"Recovery procedures not documented"}))
		rs.AddCategory(*rubric.NewCategory("testing", "DR Testing", "Disaster recovery testing plan").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Regular DR testing schedule with test scenarios, success criteria, and improvement process"}, []string{"DR testing mentioned but no schedule or criteria"}, []string{"DR testing not addressed"}))
		rs.AddCategory(*rubric.NewCategory("failover", "Failover Architecture", "Multi-region and failover design").
			SetWeight(0.1).SetRequired(false).
			WithPassPartialFail([]string{"Failover architecture documented with automatic/manual triggers and health checks"}, []string{"Basic failover info present"}, []string{"Failover architecture not addressed"}))
		Register(types.SpecType("aidlc-disaster"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-implementation-rubric", "AIDLC Implementation Plan Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Implementation Plans for task breakdown, dependencies, and risk mitigation"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("task_breakdown", "Task Breakdown", "Granularity and clarity of implementation tasks").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Tasks broken down to actionable units with clear scope, deliverables, and completion criteria"}, []string{"Tasks exist but some are too large or unclear"}, []string{"Task breakdown missing or too high-level"}))
		rs.AddCategory(*rubric.NewCategory("dependencies", "Dependencies", "Task dependencies and critical path identification").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Dependencies clearly mapped with critical path identified and blocking relationships documented"}, []string{"Some dependencies noted but incomplete mapping"}, []string{"Dependencies not identified"}))
		rs.AddCategory(*rubric.NewCategory("risk_mitigation", "Risk Mitigation", "Identification and mitigation of implementation risks").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Risks identified with probability, impact assessment, and concrete mitigation strategies"}, []string{"Some risks noted but mitigation incomplete"}, []string{"No risk assessment included"}))
		rs.AddCategory(*rubric.NewCategory("resource_allocation", "Resource Allocation", "Team and resource assignment to tasks").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Resources assigned with skills mapping and capacity planning"}, []string{"Some resource allocation present"}, []string{"No resource allocation defined"}))
		rs.AddCategory(*rubric.NewCategory("milestones", "Milestones", "Key milestones and checkpoints defined").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Clear milestones with measurable success criteria and review gates"}, []string{"Milestones exist but lack clear criteria"}, []string{"No milestones defined"}))
		Register(types.SpecType("aidlc-implementation"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-integration-rubric", "AIDLC Integration Plan Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Integration Plans for service integration, data synchronization, and rollout strategy"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("integration_points", "Integration Points", "Identification and documentation of all integration points").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"All integration points documented with protocols, data formats, and error handling"}, []string{"Integration points listed but incomplete details"}, []string{"Integration points not identified"}))
		rs.AddCategory(*rubric.NewCategory("data_sync", "Data Synchronization", "Data consistency and synchronization approach").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Data sync strategy defined with consistency requirements, conflict resolution, and rollback procedures"}, []string{"Some data sync considerations present"}, []string{"Data synchronization not addressed"}))
		rs.AddCategory(*rubric.NewCategory("rollout_strategy", "Rollout Strategy", "Phased rollout and migration approach").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Clear rollout phases with feature flags, canary deployment, and rollback triggers"}, []string{"Basic rollout plan exists but lacks detail"}, []string{"No rollout strategy defined"}))
		rs.AddCategory(*rubric.NewCategory("backwards_compatibility", "Backwards Compatibility", "API versioning and compatibility handling").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"API versioning strategy with deprecation timeline and migration guides"}, []string{"Compatibility mentioned but incomplete strategy"}, []string{"Backwards compatibility not addressed"}))
		rs.AddCategory(*rubric.NewCategory("monitoring", "Integration Monitoring", "Monitoring for integration health").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Integration monitoring defined with health checks, alerts, and dashboards"}, []string{"Some monitoring considerations present"}, []string{"Integration monitoring not addressed"}))
		Register(types.SpecType("aidlc-integration"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-monitoring-rubric", "AIDLC Monitoring Plan Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Monitoring Plans for metrics, alerting, and observability"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("metrics", "Metrics Definition", "Key metrics and their collection approach").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Key metrics defined (RED/USE) with collection method, retention policy, and dashboards"}, []string{"Some metrics defined but incomplete coverage"}, []string{"Metrics not defined"}))
		rs.AddCategory(*rubric.NewCategory("alerts", "Alerting Strategy", "Alert rules and notification channels").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Alert rules with thresholds, severity levels, and notification channels defined"}, []string{"Some alerts defined but incomplete strategy"}, []string{"Alerting not addressed"}))
		rs.AddCategory(*rubric.NewCategory("slos", "Service Level Objectives", "SLO definitions and tracking").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"SLOs defined with targets, error budgets, and burn rate alerting"}, []string{"Some SLOs mentioned but incomplete"}, []string{"SLOs not defined"}))
		rs.AddCategory(*rubric.NewCategory("logging", "Logging Strategy", "Log collection and analysis approach").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Logging strategy with log levels, structured logging, and centralized aggregation"}, []string{"Basic logging mentioned"}, []string{"Logging strategy not addressed"}))
		rs.AddCategory(*rubric.NewCategory("tracing", "Distributed Tracing", "Request tracing and correlation").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Distributed tracing implemented with correlation IDs and trace visualization"}, []string{"Tracing mentioned but incomplete"}, []string{"Distributed tracing not addressed"}))
		Register(types.SpecType("aidlc-monitoring"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-requirements-rubric", "AIDLC Requirements Specification Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Requirements Specifications for testability, traceability, and completeness"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("testability", "Testability", "Requirements are verifiable and testable").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"All requirements have clear acceptance criteria with specific, measurable test conditions"}, []string{"Most requirements testable but some lack clear acceptance criteria"}, []string{"Requirements are vague and not testable"}))
		rs.AddCategory(*rubric.NewCategory("traceability", "Traceability", "Requirements link to vision and can be traced to implementation").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Each requirement traces to vision goals with unique identifiers for tracking"}, []string{"Some traceability exists but inconsistent"}, []string{"No traceability to vision or other documents"}))
		rs.AddCategory(*rubric.NewCategory("no_ambiguity", "Clarity", "Requirements are unambiguous and clearly stated").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Requirements use precise language, avoid ambiguous terms, and have single interpretation"}, []string{"Some requirements have minor ambiguities"}, []string{"Requirements contain significant ambiguities or multiple interpretations"}))
		rs.AddCategory(*rubric.NewCategory("completeness", "Completeness", "Coverage of functional and non-functional requirements").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive coverage of functional, non-functional, and edge case requirements"}, []string{"Core requirements present but gaps in edge cases or NFRs"}, []string{"Major requirement categories missing"}))
		rs.AddCategory(*rubric.NewCategory("prioritization", "Prioritization", "Requirements are prioritized with clear rationale").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"All requirements prioritized (MoSCoW or similar) with documented rationale"}, []string{"Some prioritization exists but incomplete"}, []string{"No prioritization of requirements"}))
		Register(types.SpecType("aidlc-requirements"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-runbook-rubric", "AIDLC Runbook Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Runbooks for operational clarity, rollback procedures, and troubleshooting guidance"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("step_clarity", "Step Clarity", "Operational procedures are clear and unambiguous").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Step-by-step procedures with clear commands, expected outputs, and decision points"}, []string{"Procedures exist but some steps unclear"}, []string{"Procedures missing or too vague to follow"}))
		rs.AddCategory(*rubric.NewCategory("rollback_procedures", "Rollback Procedures", "Ability to revert changes safely").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Complete rollback procedures for each operation with verification steps"}, []string{"Some rollback info present but incomplete"}, []string{"Rollback procedures not documented"}))
		rs.AddCategory(*rubric.NewCategory("troubleshooting", "Troubleshooting", "Guidance for common issues and errors").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Troubleshooting guide with common errors, diagnostic steps, and resolution procedures"}, []string{"Some troubleshooting info present"}, []string{"No troubleshooting guidance"}))
		rs.AddCategory(*rubric.NewCategory("prerequisites", "Prerequisites", "Required access, tools, and preparation").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Prerequisites clearly listed with access requirements, tool versions, and preparation checklist"}, []string{"Some prerequisites mentioned"}, []string{"Prerequisites not documented"}))
		rs.AddCategory(*rubric.NewCategory("contacts", "Escalation Contacts", "Contact information for escalation").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Escalation path with contacts, on-call schedules, and severity guidelines"}, []string{"Some contact info present"}, []string{"Escalation contacts not documented"}))
		Register(types.SpecType("aidlc-runbook"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-security-rubric", "AIDLC Security Review Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Security Reviews for threat modeling, access control, and compliance"
		rs.PassCriteria = StrictPassCriteria()
		rs.AddCategory(*rubric.NewCategory("threat_modeling", "Threat Modeling", "Identification and analysis of security threats").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive threat model (STRIDE or similar) with attack vectors, risk ratings, and mitigations"}, []string{"Some threats identified but analysis incomplete"}, []string{"No threat modeling performed"}))
		rs.AddCategory(*rubric.NewCategory("access_control", "Access Control", "Authentication and authorization design").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Authentication/authorization mechanisms documented with least privilege, role-based access, and audit trails"}, []string{"Access control mentioned but incomplete design"}, []string{"Access control not addressed"}))
		rs.AddCategory(*rubric.NewCategory("data_protection", "Data Protection", "Encryption and sensitive data handling").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Data classification, encryption at rest/transit, and key management documented"}, []string{"Some data protection measures mentioned"}, []string{"Data protection not addressed"}))
		rs.AddCategory(*rubric.NewCategory("compliance", "Compliance", "Regulatory and compliance requirements").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Applicable compliance requirements identified (GDPR, SOC2, etc.) with controls mapped"}, []string{"Compliance mentioned but controls not mapped"}, []string{"Compliance requirements not addressed"}))
		rs.AddCategory(*rubric.NewCategory("incident_response", "Incident Response", "Security incident handling procedures").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Incident response plan with detection, escalation, and remediation procedures"}, []string{"Basic incident response considerations"}, []string{"Incident response not addressed"}))
		Register(types.SpecType("aidlc-security"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-slo-rubric", "AIDLC SLO Document Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC SLO Documents for objective clarity, measurement approach, and error budgets"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("sli_definition", "SLI Definition", "Service Level Indicator specifications").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"SLIs clearly defined with measurement method, data source, and calculation formula"}, []string{"SLIs defined but measurement approach unclear"}, []string{"SLIs not defined"}))
		rs.AddCategory(*rubric.NewCategory("slo_targets", "SLO Targets", "Service Level Objective targets").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"SLO targets defined with specific percentages, time windows, and business rationale"}, []string{"SLO targets exist but lack rationale or specificity"}, []string{"SLO targets not defined"}))
		rs.AddCategory(*rubric.NewCategory("error_budgets", "Error Budgets", "Error budget definition and policies").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Error budgets defined with burn rate alerts, exhaustion policies, and reset procedures"}, []string{"Error budgets mentioned but policies incomplete"}, []string{"Error budgets not defined"}))
		rs.AddCategory(*rubric.NewCategory("stakeholder_alignment", "Stakeholder Alignment", "Agreement between teams on objectives").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Stakeholder sign-off documented with escalation procedures and review cadence"}, []string{"Some stakeholder info present"}, []string{"Stakeholder alignment not documented"}))
		rs.AddCategory(*rubric.NewCategory("reporting", "SLO Reporting", "Regular SLO status reporting").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Reporting cadence, dashboard links, and review meeting schedule defined"}, []string{"Basic reporting mentioned"}, []string{"SLO reporting not addressed"}))
		Register(types.SpecType("aidlc-slo"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-technical-rubric", "AIDLC Technical Specification Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Technical Specifications for architecture soundness, scalability, and implementation clarity"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("architecture", "Architecture Soundness", "Technical architecture is well-designed and appropriate").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Architecture follows established patterns, addresses scalability, and includes clear component interactions"}, []string{"Architecture exists but has gaps in design or scalability considerations"}, []string{"Architecture is missing or fundamentally flawed"}))
		rs.AddCategory(*rubric.NewCategory("scalability", "Scalability", "Design addresses growth and scale requirements").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Scalability explicitly addressed with capacity planning, bottleneck analysis, and growth strategies"}, []string{"Some scalability considerations present but incomplete"}, []string{"No scalability considerations in design"}))
		rs.AddCategory(*rubric.NewCategory("implementation_clarity", "Implementation Clarity", "Technical details sufficient for implementation").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"APIs, data models, and interfaces clearly defined with sufficient detail for implementation"}, []string{"Some technical details present but gaps exist"}, []string{"Insufficient detail for implementation"}))
		rs.AddCategory(*rubric.NewCategory("technology_choices", "Technology Choices", "Technology selections are justified and appropriate").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Technology choices documented with clear rationale, alternatives considered, and trade-offs explained"}, []string{"Technologies mentioned but rationale incomplete"}, []string{"Technology choices not justified or inappropriate"}))
		rs.AddCategory(*rubric.NewCategory("dependencies", "Dependencies", "External and internal dependencies identified").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"All dependencies documented with version requirements, fallback strategies, and integration points"}, []string{"Dependencies listed but incomplete information"}, []string{"Dependencies not identified"}))
		Register(types.SpecType("aidlc-technical"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-testplan-rubric", "AIDLC Test Plan Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Test Plans for coverage, edge cases, and automation readiness"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("coverage", "Test Coverage", "Completeness of test coverage across requirements").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Test cases map to all requirements with clear traceability and coverage targets defined"}, []string{"Some coverage exists but gaps in requirement mapping"}, []string{"Test coverage incomplete or no traceability"}))
		rs.AddCategory(*rubric.NewCategory("edge_cases", "Edge Cases", "Coverage of boundary conditions and error scenarios").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Edge cases, boundary conditions, and error scenarios thoroughly documented with test cases"}, []string{"Some edge cases covered but not comprehensive"}, []string{"Edge cases not addressed"}))
		rs.AddCategory(*rubric.NewCategory("automation_readiness", "Automation Readiness", "Plan for test automation and CI/CD integration").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Clear automation strategy with tools, frameworks, and CI/CD integration plan"}, []string{"Automation mentioned but strategy incomplete"}, []string{"No automation plan included"}))
		rs.AddCategory(*rubric.NewCategory("test_data", "Test Data", "Test data strategy and management").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Test data requirements defined with generation strategy and data management plan"}, []string{"Some test data considerations present"}, []string{"Test data not addressed"}))
		rs.AddCategory(*rubric.NewCategory("environments", "Test Environments", "Test environment requirements and setup").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Test environments clearly defined with setup procedures and environment parity requirements"}, []string{"Environments mentioned but incomplete details"}, []string{"Test environments not addressed"}))
		Register(types.SpecType("aidlc-testplan"), rs)
	}
	{
		rs := rubric.NewRubricSet("aidlc-vision-rubric", "AIDLC Vision Document Evaluation", "1.0")
		rs.Description = "Evaluates AIDLC Vision Documents for clarity, stakeholder alignment, and strategic direction"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("clarity", "Vision Clarity", "Clarity and specificity of the vision statement").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Vision is clear, inspiring, and articulates a specific future state with measurable outcomes"}, []string{"Vision exists but lacks specificity or measurable outcomes"}, []string{"Vision is missing, vague, or generic without clear direction"}))
		rs.AddCategory(*rubric.NewCategory("completeness", "Completeness", "Coverage of all required vision components").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Document covers problem statement, target users, value proposition, and success criteria comprehensively"}, []string{"Some required components present but gaps exist"}, []string{"Major components missing or incomplete"}))
		rs.AddCategory(*rubric.NewCategory("alignment", "Stakeholder Alignment", "Evidence of stakeholder input and alignment").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Clear stakeholder identification, documented input, and explicit alignment with organizational goals"}, []string{"Stakeholders identified but limited evidence of alignment"}, []string{"No stakeholder alignment documented"}))
		rs.AddCategory(*rubric.NewCategory("feasibility", "Feasibility Assessment", "Realistic assessment of technical and business feasibility").
			SetWeight(0.25).SetRequired(false).
			WithPassPartialFail([]string{"Feasibility addressed with clear constraints, risks, and mitigation strategies"}, []string{"Basic feasibility mentioned but lacks depth"}, []string{"No feasibility assessment included"}))
		Register(types.SpecType("aidlc-vision"), rs)
	}
	{
		rs := rubric.NewRubricSet("faq-rubric", "FAQ Evaluation", "1.0")
		rs.Description = "Evaluates FAQ documents for completeness, clarity, and anticipation of customer questions"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("question_coverage", "Question Coverage", "Whether the FAQ anticipates the questions customers will actually ask").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive coverage of likely questions across all topics"}, []string{"Basic questions covered but gaps exist"}, []string{"Inadequate question coverage"}))
		rs.AddCategory(*rubric.NewCategory("answer_clarity", "Answer Clarity", "How clearly and directly questions are answered").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Direct, clear answers with no ambiguity"}, []string{"Answers present but could be clearer"}, []string{"Answers don't address questions"}))
		rs.AddCategory(*rubric.NewCategory("customer_language", "Customer Language", "Whether questions and answers use customer language, not internal jargon").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Questions phrased as customers would ask, answers in plain language"}, []string{"Some jargon but generally accessible"}, []string{"Written for internal audience, not customers"}))
		rs.AddCategory(*rubric.NewCategory("pricing_transparency", "Pricing Transparency", "Clarity of pricing and cost-related information").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Clear pricing with examples and cost estimation guidance"}, []string{"Basic pricing present but lacks detail"}, []string{"No pricing information"}))
		rs.AddCategory(*rubric.NewCategory("getting_started", "Getting Started Clarity", "How well the path to adoption is explained").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"Clear step-by-step path from interest to success"}, []string{"Basic getting started info present"}, []string{"No getting started guidance"}))
		rs.AddCategory(*rubric.NewCategory("objection_handling", "Objection Handling", "Whether the FAQ addresses likely concerns and objections").
			SetWeight(0.1).SetRequired(false).
			WithPassPartialFail([]string{"Proactively addresses concerns with honest, confident responses"}, []string{"Some objections covered"}, []string{"No objection handling"}))
		Register(types.SpecType("faq"), rs)
	}
	{
		rs := rubric.NewRubricSet("ird-rubric", "IRD Evaluation", "1.0")
		rs.Description = "Evaluates Infrastructure Requirements Documents for completeness, security, and operability"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("required_declarations", "Required Declarations", "Explicit declarations for IaC approach and observability pillars (VisionSpec provides no defaults)").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"IaC approach explicitly declared (Pulumi/CDK/Terraform/CloudFormation/Other/None with justification). All three observability pillars (metrics, traces, logging) explicitly declared as Implementing or None with justification."}, []string{"Some declarations present but incomplete (e.g., IaC stated but observability pillars missing, or vice versa)"}, []string{"Required declarations missing. IaC approach not stated, or observability pillars not explicitly declared."}))
		rs.AddCategory(*rubric.NewCategory("architecture_completeness", "Architecture Completeness", "Whether all infrastructure components are documented").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Complete infrastructure diagram with all components and connections"}, []string{"Basic infrastructure documented but gaps exist"}, []string{"No clear infrastructure architecture"}))
		rs.AddCategory(*rubric.NewCategory("security_design", "Security Design", "Coverage of security controls, IAM, encryption, and compliance").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive security design with IAM, encryption, secrets, and compliance"}, []string{"Basic security present but incomplete"}, []string{"No security design"}))
		rs.AddCategory(*rubric.NewCategory("availability_dr", "Availability and DR", "Coverage of availability targets, failover, and disaster recovery").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Clear SLAs, multi-region strategy, and DR procedures"}, []string{"Basic availability documented"}, []string{"No availability or DR planning"}))
		rs.AddCategory(*rubric.NewCategory("observability_implementation", "Observability Implementation", "Implementation details for declared observability pillars (must align with Section 2.2 declaration)").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"Each pillar declared as 'Implementing' has complete implementation details (platform, config, dashboards/alerts). Pillars declared as 'None' correctly marked N/A."}, []string{"Implementation details present but incomplete or inconsistent with declarations"}, []string{"No implementation details for declared pillars, or declarations contradict implementation"}))
		rs.AddCategory(*rubric.NewCategory("capacity_cost", "Capacity and Cost", "Capacity planning and cost estimation").
			SetWeight(0.1).SetRequired(false).
			WithPassPartialFail([]string{"Detailed capacity projections with cost breakdown and scaling strategy"}, []string{"Basic capacity and cost present"}, []string{"No capacity or cost planning"}))
		rs.AddCategory(*rubric.NewCategory("iac_implementation", "IaC Implementation", "Implementation details for declared IaC approach (must align with Section 2.1 declaration)").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"IaC declaration in Section 2.1 has corresponding implementation details (repo, modules, CI/CD). If 'No IaC' declared, manual procedures documented."}, []string{"IaC mentioned but implementation incomplete or inconsistent with declaration"}, []string{"No IaC implementation details, or implementation contradicts Section 2.1 declaration"}))
		rs.AddCategory(*rubric.NewCategory("operability", "Operability", "Whether infrastructure can be operated and maintained").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"Clear CI/CD infrastructure, runbooks, and operational procedures aligned with IaC choice"}, []string{"Basic operational procedures"}, []string{"Cannot be operated from this document"}))
		Register(types.SpecType("ird"), rs)
	}
	{
		rs := rubric.NewRubricSet("mrd-rubric", "MRD Evaluation", "1.0")
		rs.Description = "Evaluates Market Requirements Documents for completeness, clarity, and market insight"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("problem_statement", "Problem Statement", "Clarity and relevance of the market problem being addressed").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Problem is clearly articulated with quantified impact, timing justification, and cost of inaction"}, []string{"Problem is stated but lacks depth or supporting evidence"}, []string{"Problem statement is missing or unclear"}))
		rs.AddCategory(*rubric.NewCategory("target_market", "Target Market", "Definition and sizing of target market segments").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Clear TAM/SAM/SOM with detailed segment profiles and sizing methodology"}, []string{"Basic market definition present but incomplete"}, []string{"Market definition missing or completely inadequate"}))
		rs.AddCategory(*rubric.NewCategory("competitive_analysis", "Competitive Analysis", "Understanding of competitive landscape and differentiation").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Comprehensive analysis of direct/indirect competitors with clear differentiation strategy"}, []string{"Basic competitor list but limited analysis"}, []string{"Competitive analysis missing"}))
		rs.AddCategory(*rubric.NewCategory("requirements_clarity", "Requirements Clarity", "Clarity and prioritization of market requirements").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Requirements are prioritized (MoSCoW), traceable, and well-rationalized"}, []string{"Requirements listed but prioritization is weak"}, []string{"Requirements section is inadequate"}))
		rs.AddCategory(*rubric.NewCategory("business_alignment", "Business Alignment", "Alignment with business goals and measurable success metrics").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Clear strategic alignment with quantified success metrics and timelines"}, []string{"Business alignment stated but metrics are weak"}, []string{"No clear business alignment"}))
		rs.AddCategory(*rubric.NewCategory("risk_assessment", "Risk Assessment", "Identification of constraints, assumptions, and risks").
			SetWeight(0.1).SetRequired(false).
			WithPassPartialFail([]string{"Comprehensive risk matrix with impact, probability, and mitigation strategies"}, []string{"Risks listed but mitigation is incomplete"}, []string{"Risk assessment missing"}))
		Register(types.SpecType("mrd"), rs)
	}
	{
		rs := rubric.NewRubricSet("narrative-1p-rubric", "Narrative 1-Pager Evaluation", "1.0")
		rs.Description = "Evaluates Executive 1-Pager narratives for clarity, impact, and completeness"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("opportunity_clarity", "Opportunity Clarity", "How clearly the market opportunity or problem is articulated").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Compelling opportunity with clear market timing and urgency"}, []string{"Opportunity stated but lacks compelling urgency"}, []string{"No clear opportunity articulated or poorly justified"}))
		rs.AddCategory(*rubric.NewCategory("solution_value", "Solution Value Proposition", "Clarity of the solution and its value proposition").
			SetWeight(0.25).SetRequired(true).
			WithPassPartialFail([]string{"Crystal clear value proposition with direct link to opportunity"}, []string{"Solution described but value unclear"}, []string{"No clear solution articulated or disconnected from problem"}))
		rs.AddCategory(*rubric.NewCategory("target_specificity", "Target Customer Specificity", "How specifically the target customer is defined").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Specific, well-defined customer segment with clear characteristics"}, []string{"Customer mentioned but too broad"}, []string{"No target customer defined or definition is vague"}))
		rs.AddCategory(*rubric.NewCategory("benefits_concrete", "Concrete Benefits", "Whether benefits are outcome-focused and concrete").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Benefits are specific, measurable outcomes customers care about"}, []string{"Benefits listed but feature-focused rather than outcome-focused"}, []string{"No clear benefits stated or benefits are vague"}))
		rs.AddCategory(*rubric.NewCategory("ask_clarity", "Clear Ask", "Whether the ask (resources, decisions needed) is clear").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Specific ask with clear next steps and timeline"}, []string{"Ask present but vague on specifics"}, []string{"No ask or call to action"}))
		Register(types.SpecType("narrative-1p"), rs)
	}
	{
		rs := rubric.NewRubricSet("narrative-6p-rubric", "Narrative 6-Pager Evaluation", "1.0")
		rs.Description = "Evaluates AWS-style 6-pager narratives for depth, rigor, and completeness"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("tenets_clarity", "Tenets and Introduction", "Quality of guiding principles and context setting").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"Clear, actionable tenets that guide tradeoff decisions"}, []string{"Tenets present but generic or not actionable"}, []string{"No tenets or introduction"}))
		rs.AddCategory(*rubric.NewCategory("customer_depth", "Customer Problem Depth", "How deeply the customer and their problem are understood").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Specific customer with vivid problem description, quotes, and anecdotes"}, []string{"Customer and problem described but lacks depth"}, []string{"No meaningful customer or problem description"}))
		rs.AddCategory(*rubric.NewCategory("solution_narrative", "Solution Narrative", "Quality of the customer-centric solution description").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Compelling customer journey with clear capabilities and scope"}, []string{"Solution described but too technical or feature-focused"}, []string{"No coherent solution narrative"}))
		rs.AddCategory(*rubric.NewCategory("timing_justification", "Why Now Justification", "Strength of the timing and urgency argument").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Compelling market, competitive, and internal readiness arguments"}, []string{"Timing argument present but weak"}, []string{"No timing justification or convincing reason for urgency"}))
		rs.AddCategory(*rubric.NewCategory("business_case", "Business Case Rigor", "Quality of customer impact, business metrics, and ROI analysis").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Quantified customer and business impact with clear assumptions"}, []string{"Some metrics but lacking rigor or assumptions"}, []string{"No business case or weak unsupported claims"}))
		rs.AddCategory(*rubric.NewCategory("risks_dependencies", "Risks and Dependencies", "Thoroughness of risk identification and mitigation").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive risks with likelihood, impact, and mitigations"}, []string{"Some risks listed but incomplete analysis"}, []string{"No risk assessment"}))
		Register(types.SpecType("narrative-6p"), rs)
	}
	{
		rs := rubric.NewRubricSet("prd-rubric", "PRD Evaluation", "1.0")
		rs.Description = "Evaluates Product Requirements Documents for completeness, testability, and clarity"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("problem_definition", "Problem Definition", "Clarity of the problem statement from user perspective").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Problem is specific, measurable, and clearly impacts users"}, []string{"Problem exists but lacks specificity"}, []string{"No clear problem statement"}))
		rs.AddCategory(*rubric.NewCategory("goals_scope", "Goals and Scope", "Clarity of goals and explicit non-goals").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Goals are SMART, non-goals explicitly stated, scope is bounded"}, []string{"Goals present but scope could be clearer"}, []string{"Goals and scope missing"}))
		rs.AddCategory(*rubric.NewCategory("user_stories", "User Stories", "Quality and completeness of user stories").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"All stories follow standard format, are prioritized, with clear acceptance criteria"}, []string{"Stories exist but some lack acceptance criteria"}, []string{"User stories missing or inadequate"}))
		rs.AddCategory(*rubric.NewCategory("functional_requirements", "Functional Requirements", "Completeness and testability of functional requirements").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Requirements are complete, traceable to stories, and testable"}, []string{"Requirements exist but some are vague"}, []string{"Functional requirements missing"}))
		rs.AddCategory(*rubric.NewCategory("nonfunctional_requirements", "Non-Functional Requirements", "Coverage of performance, security, reliability requirements").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Comprehensive NFRs with measurable targets for performance, security, accessibility"}, []string{"Some NFRs present but incomplete coverage"}, []string{"NFRs missing"}))
		rs.AddCategory(*rubric.NewCategory("success_metrics", "Success Metrics", "Definition of measurable success criteria").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"SMART metrics with baselines, targets, and measurement methods"}, []string{"Some metrics but lacking specificity"}, []string{"Success metrics missing"}))
		rs.AddCategory(*rubric.NewCategory("dependencies", "Dependencies and Risks", "Identification of dependencies and open questions").
			SetWeight(0.05).SetRequired(false).
			WithPassPartialFail([]string{"Dependencies mapped with owners, status, and risk mitigation"}, []string{"Some dependencies noted"}, []string{"Dependencies not addressed"}))
		Register(types.SpecType("prd"), rs)
	}
	{
		rs := rubric.NewRubricSet("press-rubric", "Press Release Evaluation", "1.0")
		rs.Description = "Evaluates Press Release documents for clarity, customer focus, and completeness"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("headline_impact", "Headline Impact", "Whether the headline clearly communicates the primary customer benefit").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Compelling headline with clear customer benefit and urgency"}, []string{"Headline present but benefit unclear"}, []string{"No clear headline or irrelevant"}))
		rs.AddCategory(*rubric.NewCategory("customer_problem", "Customer Problem", "How well the customer problem is articulated with authentic voice").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Vivid problem description with authentic customer quotes"}, []string{"Problem stated but lacks customer voice"}, []string{"No clear customer problem"}))
		rs.AddCategory(*rubric.NewCategory("solution_clarity", "Solution Clarity", "Whether the solution and benefits are clearly explained").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Crystal clear solution with concrete, measurable benefits"}, []string{"Solution described but benefits vague"}, []string{"No clear solution articulated"}))
		rs.AddCategory(*rubric.NewCategory("customer_validation", "Customer Validation", "Quality of customer quotes and validation").
			SetWeight(0.15).SetRequired(false).
			WithPassPartialFail([]string{"Authentic customer quotes with specific success stories"}, []string{"Generic quotes without specificity"}, []string{"No customer validation"}))
		rs.AddCategory(*rubric.NewCategory("call_to_action", "Call to Action", "Clarity of availability, pricing, and next steps").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Clear availability, pricing, and specific action steps"}, []string{"CTA present but vague"}, []string{"No call to action"}))
		rs.AddCategory(*rubric.NewCategory("readability", "Readability", "Whether the press release is written in plain, accessible language").
			SetWeight(0.1).SetRequired(false).
			WithPassPartialFail([]string{"Clear, jargon-free prose accessible to general audience"}, []string{"Somewhat technical but understandable"}, []string{"Incomprehensible to target audience"}))
		Register(types.SpecType("press"), rs)
	}
	{
		rs := rubric.NewRubricSet("trd-rubric", "TRD Evaluation", "1.0")
		rs.Description = "Evaluates Technical Requirements Documents for completeness, clarity, and implementability"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("architecture_clarity", "Architecture Clarity", "How clearly the system architecture is described").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Clear architecture with diagrams, component descriptions, and data flow"}, []string{"Basic architecture present but lacks detail"}, []string{"No clear architecture described"}))
		rs.AddCategory(*rubric.NewCategory("prd_traceability", "PRD Traceability", "Whether technical design traces back to PRD requirements").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Every PRD requirement has corresponding technical design"}, []string{"Some traceability but gaps exist"}, []string{"No traceability to requirements"}))
		rs.AddCategory(*rubric.NewCategory("api_design", "API Design", "Quality of API/interface definitions").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Complete API spec with request/response schemas and error handling"}, []string{"Basic API definition present"}, []string{"No API design"}))
		rs.AddCategory(*rubric.NewCategory("data_design", "Data Design", "Quality of data models and storage design").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Complete data models with relationships, storage rationale, and migration plan"}, []string{"Basic data design present"}, []string{"No data design"}))
		rs.AddCategory(*rubric.NewCategory("nfr_coverage", "NFR Coverage", "Coverage of non-functional requirements (performance, security, etc.)").
			SetWeight(0.2).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive NFRs with specific targets and measurement plans"}, []string{"Some NFRs but gaps in coverage"}, []string{"No NFR coverage"}))
		rs.AddCategory(*rubric.NewCategory("implementability", "Implementability", "Whether the design is implementable by an engineer").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Design is actionable with clear path to implementation"}, []string{"Design needs some clarification before implementation"}, []string{"Cannot be implemented from this document"}))
		Register(types.SpecType("trd"), rs)
	}
	{
		rs := rubric.NewRubricSet("uxd-rubric", "UXD Evaluation", "1.0")
		rs.Description = "Evaluates User Experience Design documents for usability, accessibility, and completeness"
		rs.PassCriteria = DefaultPassCriteria()
		rs.AddCategory(*rubric.NewCategory("design_goals", "Design Goals", "Clarity of UX objectives and design principles").
			SetWeight(0.1).SetRequired(true).
			WithPassPartialFail([]string{"Clear, measurable UX goals aligned with product strategy and guiding principles"}, []string{"Goals present but could be more specific"}, []string{"Design goals missing"}))
		rs.AddCategory(*rubric.NewCategory("user_personas", "User Personas", "Quality and depth of user persona definitions").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Rich personas with goals, pain points, behaviors, and scenarios"}, []string{"Basic personas present but shallow"}, []string{"Personas missing or inadequate"}))
		rs.AddCategory(*rubric.NewCategory("user_journeys", "User Journeys", "Completeness of user journey mapping").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Complete journeys with entry/exit points, success criteria, and edge cases"}, []string{"Basic flows present but incomplete"}, []string{"User journeys missing"}))
		rs.AddCategory(*rubric.NewCategory("information_architecture", "Information Architecture", "Structure and organization of content").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Clear site map, navigation structure, and content hierarchy"}, []string{"Basic structure present"}, []string{"Information architecture missing"}))
		rs.AddCategory(*rubric.NewCategory("wireframes", "Wireframes and Layouts", "Quality and coverage of wireframes").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"Comprehensive wireframes for all key screens with element descriptions"}, []string{"Some wireframes but incomplete coverage"}, []string{"Wireframes missing"}))
		rs.AddCategory(*rubric.NewCategory("interaction_design", "Interaction Design", "Definition of interaction patterns and behaviors").
			SetWeight(0.1).SetRequired(false).
			WithPassPartialFail([]string{"Clear interaction patterns, micro-interactions, and state transitions"}, []string{"Basic interactions present"}, []string{"Interaction design missing"}))
		rs.AddCategory(*rubric.NewCategory("accessibility", "Accessibility", "WCAG compliance and inclusive design considerations").
			SetWeight(0.15).SetRequired(true).
			WithPassPartialFail([]string{"WCAG compliance specified, comprehensive checklist, keyboard/screen reader considerations"}, []string{"Basic accessibility mentioned"}, []string{"Accessibility not addressed"}))
		rs.AddCategory(*rubric.NewCategory("error_states", "Error States and Edge Cases", "Handling of errors, empty states, and edge cases").
			SetWeight(0.05).SetRequired(false).
			WithPassPartialFail([]string{"Comprehensive error messages, empty states, loading states, and recovery actions"}, []string{"Some error states defined"}, []string{"Error states not addressed"}))
		Register(types.SpecType("uxd"), rs)
	}
}
