package testgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func init() {
	Register(&GoGenerator{})
}

// GoGenerator generates Go test stubs.
type GoGenerator struct{}

// Language returns the language name.
func (g *GoGenerator) Language() string {
	return "go"
}

// Generate creates Go test files from test cases.
func (g *GoGenerator) Generate(cases []TestCase, opts GenerateOptions) (*GenerateResult, error) {
	if opts.OutputDir == "" {
		opts.OutputDir = "."
	}
	if opts.PackageName == "" {
		opts.PackageName = "tests"
	}

	framework := opts.TestFramework
	if framework == "" {
		framework = "testing"
	}

	// Create output directory
	if err := os.MkdirAll(opts.OutputDir, 0755); err != nil {
		return nil, fmt.Errorf("creating output directory: %w", err)
	}

	result := &GenerateResult{
		Language:    "go",
		Framework:   framework,
		OutputDir:   opts.OutputDir,
		GeneratedAt: time.Now(),
	}

	// Group tests
	var grouped map[string][]TestCase
	switch opts.GroupBy {
	case "priority":
		grouped = g.groupByPriority(cases)
	case "file":
		grouped = g.groupByFile(cases)
	default:
		grouped = g.groupByType(cases)
	}

	// Generate files
	for groupName, groupCases := range grouped {
		content := g.generateFile(opts.PackageName, groupName, groupCases, framework)
		filename := g.makeFilename(groupName)
		filePath := filepath.Join(opts.OutputDir, filename)

		if err := os.WriteFile(filePath, []byte(content), 0600); err != nil {
			return nil, fmt.Errorf("writing %s: %w", filename, err)
		}

		result.Files = append(result.Files, GeneratedFile{
			Path:      filePath,
			TestCount: len(groupCases),
			Content:   content,
		})
		result.TotalTests += len(groupCases)
	}

	return result, nil
}

func (g *GoGenerator) groupByType(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := string(tc.Type)
		if key == "" {
			key = "functional"
		}
		result[key] = append(result[key], tc)
	}
	return result
}

func (g *GoGenerator) groupByPriority(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := tc.Priority
		if key == "" {
			key = "p2"
		}
		result[strings.ToLower(key)] = append(result[strings.ToLower(key)], tc)
	}
	return result
}

func (g *GoGenerator) groupByFile(cases []TestCase) map[string][]TestCase {
	// Group by source reference or type
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := tc.SourceRef
		if key == "" {
			key = string(tc.Type)
		}
		if key == "" {
			key = "general"
		}
		result[key] = append(result[key], tc)
	}
	return result
}

func (g *GoGenerator) makeFilename(groupName string) string {
	name := strings.ToLower(groupName)
	name = strings.ReplaceAll(name, " ", "_")
	name = strings.ReplaceAll(name, "-", "_")
	return name + "_test.go"
}

func (g *GoGenerator) generateFile(pkg, group string, cases []TestCase, framework string) string {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("// Code generated by visionspec testgen. DO NOT EDIT.\n"))
	sb.WriteString(fmt.Sprintf("// Source: TPD section for %s tests\n\n", group))
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	// Imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"testing\"\n")
	if framework == "testify" {
		sb.WriteString("\n")
		sb.WriteString("\t\"github.com/stretchr/testify/assert\"\n")
		sb.WriteString("\t\"github.com/stretchr/testify/require\"\n")
	}
	sb.WriteString(")\n\n")

	// Generate test functions
	for _, tc := range cases {
		sb.WriteString(g.generateTestFunc(tc, framework))
		sb.WriteString("\n")
	}

	return sb.String()
}

func (g *GoGenerator) generateTestFunc(tc TestCase, framework string) string {
	var sb strings.Builder

	funcName := g.makeFuncName(tc)

	// Doc comment
	sb.WriteString(fmt.Sprintf("// %s tests: %s\n", funcName, tc.Title))
	if tc.SourceRef != "" {
		sb.WriteString(fmt.Sprintf("// Source: %s\n", tc.SourceRef))
	}
	sb.WriteString(fmt.Sprintf("// Priority: %s\n", tc.Priority))

	// Function signature
	sb.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", funcName))

	// Test body
	if framework == "testify" {
		sb.WriteString(g.generateTestifyBody(tc))
	} else {
		sb.WriteString(g.generateStandardBody(tc))
	}

	sb.WriteString("}\n")

	return sb.String()
}

func (g *GoGenerator) makeFuncName(tc TestCase) string {
	// Start with Test prefix
	name := "Test"

	// Add type prefix
	switch tc.Type {
	case TestTypeAPI:
		name += "API_"
	case TestTypeIntegration:
		name += "Integration_"
	case TestTypeE2E:
		name += "E2E_"
	case TestTypePerformance:
		name += "Perf_"
	case TestTypeUAT:
		name += "UAT_"
	default:
		name += "Func_"
	}

	// Add ID if present
	if tc.ID != "" {
		id := strings.ReplaceAll(tc.ID, "-", "_")
		name += id + "_"
	}

	// Add sanitized title
	title := tc.Title
	title = strings.ReplaceAll(title, " ", "_")
	title = strings.ReplaceAll(title, "-", "_")
	title = strings.ReplaceAll(title, ":", "")
	title = strings.ReplaceAll(title, "/", "_")
	title = strings.ReplaceAll(title, ".", "_")

	// Keep only alphanumeric and underscore
	var sanitized strings.Builder
	for _, r := range title {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			sanitized.WriteRune(r)
		}
	}
	name += sanitized.String()

	// Truncate if too long
	if len(name) > 100 {
		name = name[:100]
	}

	return name
}

func (g *GoGenerator) generateStandardBody(tc TestCase) string {
	var sb strings.Builder

	sb.WriteString("\tt.Helper()\n\n")

	// Test setup comment
	sb.WriteString("\t// TODO: Setup\n")
	if tc.Input != "" {
		sb.WriteString(fmt.Sprintf("\t// Input: %s\n", tc.Input))
	}
	sb.WriteString("\n")

	// Steps if present
	if len(tc.Steps) > 0 {
		sb.WriteString("\t// Steps:\n")
		for i, step := range tc.Steps {
			sb.WriteString(fmt.Sprintf("\t// %d. %s\n", i+1, step))
		}
		sb.WriteString("\n")
	}

	// Expected result
	sb.WriteString("\t// TODO: Execute test\n")
	sb.WriteString("\tvar got interface{}\n")
	sb.WriteString("\t_ = got\n\n")

	// Assertion
	sb.WriteString("\t// TODO: Verify\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("\t// Expected: %s\n", tc.Expected))
	}
	sb.WriteString("\t// if got != want {\n")
	sb.WriteString("\t// \tt.Errorf(\"got %v, want %v\", got, want)\n")
	sb.WriteString("\t// }\n")
	sb.WriteString("\n")

	// Placeholder fail
	sb.WriteString("\tt.Skip(\"TODO: Implement test\")\n")

	return sb.String()
}

func (g *GoGenerator) generateTestifyBody(tc TestCase) string {
	var sb strings.Builder

	sb.WriteString("\tt.Helper()\n\n")

	// Test setup comment
	sb.WriteString("\t// TODO: Setup\n")
	if tc.Input != "" {
		sb.WriteString(fmt.Sprintf("\t// Input: %s\n", tc.Input))
	}
	sb.WriteString("\n")

	// Steps if present
	if len(tc.Steps) > 0 {
		sb.WriteString("\t// Steps:\n")
		for i, step := range tc.Steps {
			sb.WriteString(fmt.Sprintf("\t// %d. %s\n", i+1, step))
		}
		sb.WriteString("\n")
	}

	// Declare require/assert (silence unused import)
	sb.WriteString("\t_ = assert.New(t)\n")
	sb.WriteString("\t_ = require.New(t)\n\n")

	// Expected result
	sb.WriteString("\t// TODO: Execute test\n")
	sb.WriteString("\tvar got interface{}\n")
	sb.WriteString("\t_ = got\n\n")

	// Assertion
	sb.WriteString("\t// TODO: Verify\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("\t// Expected: %s\n", tc.Expected))
	}
	sb.WriteString("\t// assert.Equal(t, want, got)\n")
	sb.WriteString("\n")

	// Placeholder fail
	sb.WriteString("\tt.Skip(\"TODO: Implement test\")\n")

	return sb.String()
}
