package testgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func init() {
	Register(&PythonGenerator{})
}

// PythonGenerator generates Python/pytest test stubs.
type PythonGenerator struct{}

// Language returns the language name.
func (g *PythonGenerator) Language() string {
	return "py"
}

// Generate creates Python test files from test cases.
func (g *PythonGenerator) Generate(cases []TestCase, opts GenerateOptions) (*GenerateResult, error) {
	if opts.OutputDir == "" {
		opts.OutputDir = "."
	}

	framework := opts.TestFramework
	if framework == "" {
		framework = "pytest"
	}

	// Create output directory
	if err := os.MkdirAll(opts.OutputDir, 0755); err != nil {
		return nil, fmt.Errorf("creating output directory: %w", err)
	}

	result := &GenerateResult{
		Language:    "python",
		Framework:   framework,
		OutputDir:   opts.OutputDir,
		GeneratedAt: time.Now(),
	}

	// Group tests
	var grouped map[string][]TestCase
	switch opts.GroupBy {
	case "priority":
		grouped = g.groupByPriority(cases)
	case "file":
		grouped = g.groupByFile(cases)
	default:
		grouped = g.groupByType(cases)
	}

	// Generate files
	for groupName, groupCases := range grouped {
		content := g.generateFile(groupName, groupCases, framework)
		filename := g.makeFilename(groupName)
		filePath := filepath.Join(opts.OutputDir, filename)

		if err := os.WriteFile(filePath, []byte(content), 0600); err != nil {
			return nil, fmt.Errorf("writing %s: %w", filename, err)
		}

		result.Files = append(result.Files, GeneratedFile{
			Path:      filePath,
			TestCount: len(groupCases),
			Content:   content,
		})
		result.TotalTests += len(groupCases)
	}

	// Generate conftest.py if needed
	conftestPath := filepath.Join(opts.OutputDir, "conftest.py")
	if _, err := os.Stat(conftestPath); os.IsNotExist(err) {
		conftest := g.generateConftest()
		if err := os.WriteFile(conftestPath, []byte(conftest), 0600); err != nil {
			return nil, fmt.Errorf("writing conftest.py: %w", err)
		}
		result.Files = append(result.Files, GeneratedFile{
			Path:      conftestPath,
			TestCount: 0,
			Content:   conftest,
		})
	}

	return result, nil
}

func (g *PythonGenerator) groupByType(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := string(tc.Type)
		if key == "" {
			key = "functional"
		}
		result[key] = append(result[key], tc)
	}
	return result
}

func (g *PythonGenerator) groupByPriority(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := tc.Priority
		if key == "" {
			key = "p2"
		}
		result[strings.ToLower(key)] = append(result[strings.ToLower(key)], tc)
	}
	return result
}

func (g *PythonGenerator) groupByFile(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := tc.SourceRef
		if key == "" {
			key = string(tc.Type)
		}
		if key == "" {
			key = "general"
		}
		result[key] = append(result[key], tc)
	}
	return result
}

func (g *PythonGenerator) makeFilename(groupName string) string {
	name := strings.ToLower(groupName)
	name = strings.ReplaceAll(name, " ", "_")
	name = strings.ReplaceAll(name, "-", "_")
	return "test_" + name + ".py"
}

func (g *PythonGenerator) generateFile(group string, cases []TestCase, framework string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("\"\"\"")
	sb.WriteString(fmt.Sprintf("\nCode generated by visionspec testgen. DO NOT EDIT.\n"))
	sb.WriteString(fmt.Sprintf("Source: TPD section for %s tests\n", group))
	sb.WriteString("\"\"\"\n\n")

	// Imports
	sb.WriteString("import pytest\n")

	// Add specific imports based on test types
	hasAPI := false
	hasE2E := false
	for _, tc := range cases {
		if tc.Type == TestTypeAPI {
			hasAPI = true
		}
		if tc.Type == TestTypeE2E {
			hasE2E = true
		}
	}

	if hasAPI {
		sb.WriteString("# import requests  # Uncomment when implementing API tests\n")
	}
	if hasE2E {
		sb.WriteString("# from playwright.sync_api import Page  # Uncomment for E2E tests\n")
	}
	sb.WriteString("\n\n")

	// Generate test class
	className := g.formatClassName(group)
	sb.WriteString(fmt.Sprintf("class Test%s:\n", className))
	sb.WriteString(fmt.Sprintf("    \"\"\"%s Tests\"\"\"\n\n", className))

	// Generate test methods
	for _, tc := range cases {
		sb.WriteString(g.generateTestMethod(tc, framework))
	}

	return sb.String()
}

func (g *PythonGenerator) formatClassName(group string) string {
	// Convert to PascalCase
	words := strings.FieldsFunc(group, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	for i, word := range words {
		if len(word) > 0 {
			words[i] = strings.ToUpper(string(word[0])) + strings.ToLower(word[1:])
		}
	}
	return strings.Join(words, "")
}

func (g *PythonGenerator) generateTestMethod(tc TestCase, _ string) string {
	var sb strings.Builder

	methodName := g.makeMethodName(tc)

	// Priority marker
	if tc.Priority == "P0" {
		sb.WriteString("    @pytest.mark.critical\n")
	} else if tc.Priority == "P1" {
		sb.WriteString("    @pytest.mark.high\n")
	}

	// Skip marker (will be removed when implemented)
	sb.WriteString("    @pytest.mark.skip(reason=\"TODO: Implement test\")\n")

	// Method signature
	sb.WriteString(fmt.Sprintf("    def %s(self):\n", methodName))

	// Docstring
	sb.WriteString(fmt.Sprintf("        \"\"\"%s\n", tc.Title))
	if tc.SourceRef != "" {
		sb.WriteString(fmt.Sprintf("        Source: %s\n", tc.SourceRef))
	}
	sb.WriteString(fmt.Sprintf("        Priority: %s\n", tc.Priority))
	sb.WriteString("        \"\"\"\n")

	// Test body based on type
	switch tc.Type {
	case TestTypeAPI:
		sb.WriteString(g.generateAPIBody(tc))
	case TestTypeE2E:
		sb.WriteString(g.generateE2EBody(tc))
	default:
		sb.WriteString(g.generateFunctionalBody(tc))
	}

	sb.WriteString("\n")

	return sb.String()
}

func (g *PythonGenerator) makeMethodName(tc TestCase) string {
	name := "test_"

	// Add type prefix
	switch tc.Type {
	case TestTypeAPI:
		name += "api_"
	case TestTypeIntegration:
		name += "integration_"
	case TestTypeE2E:
		name += "e2e_"
	case TestTypePerformance:
		name += "perf_"
	case TestTypeUAT:
		name += "uat_"
	}

	// Add ID if present
	if tc.ID != "" {
		id := strings.ToLower(tc.ID)
		id = strings.ReplaceAll(id, "-", "_")
		name += id + "_"
	}

	// Add sanitized title
	title := strings.ToLower(tc.Title)
	title = strings.ReplaceAll(title, " ", "_")
	title = strings.ReplaceAll(title, "-", "_")
	title = strings.ReplaceAll(title, ":", "")
	title = strings.ReplaceAll(title, "/", "_")
	title = strings.ReplaceAll(title, ".", "_")

	// Keep only alphanumeric and underscore
	var sanitized strings.Builder
	for _, r := range title {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			sanitized.WriteRune(r)
		}
	}
	name += sanitized.String()

	// Remove consecutive underscores
	for strings.Contains(name, "__") {
		name = strings.ReplaceAll(name, "__", "_")
	}

	// Truncate if too long
	if len(name) > 100 {
		name = name[:100]
	}

	// Remove trailing underscore
	name = strings.TrimSuffix(name, "_")

	return name
}

func (g *PythonGenerator) generateFunctionalBody(tc TestCase) string {
	var sb strings.Builder

	// Setup
	sb.WriteString("        # Setup\n")
	if tc.Input != "" {
		sb.WriteString(fmt.Sprintf("        # Input: %s\n", tc.Input))
	}
	sb.WriteString("\n")

	// Steps
	if len(tc.Steps) > 0 {
		sb.WriteString("        # Steps:\n")
		for i, step := range tc.Steps {
			sb.WriteString(fmt.Sprintf("        # %d. %s\n", i+1, step))
		}
		sb.WriteString("\n")
	}

	// Execute
	sb.WriteString("        # Execute\n")
	sb.WriteString("        result = None  # TODO: Call function under test\n\n")

	// Verify
	sb.WriteString("        # Verify\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("        # Expected: %s\n", tc.Expected))
	}
	sb.WriteString("        # assert result == expected\n")
	sb.WriteString("        assert False, \"TODO: Implement test\"\n")

	return sb.String()
}

func (g *PythonGenerator) generateAPIBody(tc TestCase) string {
	var sb strings.Builder

	// Setup
	sb.WriteString("        # API Test Setup\n")
	sb.WriteString("        # client = requests.Session()\n")
	sb.WriteString("        # base_url = \"http://localhost:8000\"\n\n")

	// Request
	if tc.Input != "" {
		sb.WriteString(fmt.Sprintf("        # Request: %s\n", tc.Input))
	}
	sb.WriteString("        # response = client.get(f\"{base_url}/endpoint\")\n\n")

	// Verify
	sb.WriteString("        # Verify Response\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("        # Expected: %s\n", tc.Expected))
	}
	sb.WriteString("        # assert response.status_code == 200\n")
	sb.WriteString("        # assert response.json() == {...}\n")
	sb.WriteString("        assert False, \"TODO: Implement API test\"\n")

	return sb.String()
}

func (g *PythonGenerator) generateE2EBody(tc TestCase) string {
	var sb strings.Builder

	// Setup
	sb.WriteString("        # E2E Test Setup\n")
	sb.WriteString("        # page: Page = self.page  # Playwright page\n\n")

	// Journey steps
	if len(tc.Steps) > 0 {
		sb.WriteString("        # User Journey Steps:\n")
		for i, step := range tc.Steps {
			sb.WriteString(fmt.Sprintf("        # Step %d: %s\n", i+1, step))
		}
		sb.WriteString("\n")
	}

	// Execute
	sb.WriteString("        # Execute Journey\n")
	sb.WriteString("        # page.goto(\"/\")\n")
	sb.WriteString("        # page.click(\"button\")\n\n")

	// Verify
	sb.WriteString("        # Verify Outcome\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("        # Assertions: %s\n", tc.Expected))
	}
	sb.WriteString("        # expect(page.locator(\"...\")).to_be_visible()\n")
	sb.WriteString("        assert False, \"TODO: Implement E2E test\"\n")

	return sb.String()
}

func (g *PythonGenerator) generateConftest() string {
	return `"""
Pytest configuration and fixtures.
Generated by visionspec testgen.
"""
import pytest


# Add custom markers
def pytest_configure(config):
    """Register custom markers."""
    config.addinivalue_line("markers", "critical: mark test as critical (P0)")
    config.addinivalue_line("markers", "high: mark test as high priority (P1)")


# Example fixtures - uncomment and customize as needed

# @pytest.fixture
# def client():
#     """API client fixture."""
#     import requests
#     session = requests.Session()
#     yield session
#     session.close()


# @pytest.fixture
# def page():
#     """Browser page fixture for E2E tests."""
#     from playwright.sync_api import sync_playwright
#     with sync_playwright() as p:
#         browser = p.chromium.launch()
#         page = browser.new_page()
#         yield page
#         browser.close()
`
}
