package testgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func init() {
	Register(&TypeScriptGenerator{})
}

// TypeScriptGenerator generates TypeScript/Jest test stubs.
type TypeScriptGenerator struct{}

// Language returns the language name.
func (g *TypeScriptGenerator) Language() string {
	return "ts"
}

// Generate creates TypeScript test files from test cases.
func (g *TypeScriptGenerator) Generate(cases []TestCase, opts GenerateOptions) (*GenerateResult, error) {
	if opts.OutputDir == "" {
		opts.OutputDir = "."
	}

	framework := opts.TestFramework
	if framework == "" {
		framework = "jest"
	}

	// Create output directory
	if err := os.MkdirAll(opts.OutputDir, 0755); err != nil {
		return nil, fmt.Errorf("creating output directory: %w", err)
	}

	result := &GenerateResult{
		Language:    "typescript",
		Framework:   framework,
		OutputDir:   opts.OutputDir,
		GeneratedAt: time.Now(),
	}

	// Group tests
	var grouped map[string][]TestCase
	switch opts.GroupBy {
	case "priority":
		grouped = g.groupByPriority(cases)
	case "file":
		grouped = g.groupByFile(cases)
	default:
		grouped = g.groupByType(cases)
	}

	// Generate files
	for groupName, groupCases := range grouped {
		content := g.generateFile(groupName, groupCases, framework)
		filename := g.makeFilename(groupName, framework)
		filePath := filepath.Join(opts.OutputDir, filename)

		if err := os.WriteFile(filePath, []byte(content), 0600); err != nil {
			return nil, fmt.Errorf("writing %s: %w", filename, err)
		}

		result.Files = append(result.Files, GeneratedFile{
			Path:      filePath,
			TestCount: len(groupCases),
			Content:   content,
		})
		result.TotalTests += len(groupCases)
	}

	return result, nil
}

func (g *TypeScriptGenerator) groupByType(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := string(tc.Type)
		if key == "" {
			key = "functional"
		}
		result[key] = append(result[key], tc)
	}
	return result
}

func (g *TypeScriptGenerator) groupByPriority(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := tc.Priority
		if key == "" {
			key = "p2"
		}
		result[strings.ToLower(key)] = append(result[strings.ToLower(key)], tc)
	}
	return result
}

func (g *TypeScriptGenerator) groupByFile(cases []TestCase) map[string][]TestCase {
	result := make(map[string][]TestCase)
	for _, tc := range cases {
		key := tc.SourceRef
		if key == "" {
			key = string(tc.Type)
		}
		if key == "" {
			key = "general"
		}
		result[key] = append(result[key], tc)
	}
	return result
}

func (g *TypeScriptGenerator) makeFilename(groupName, framework string) string {
	name := strings.ToLower(groupName)
	name = strings.ReplaceAll(name, " ", "-")
	name = strings.ReplaceAll(name, "_", "-")

	switch framework {
	case "vitest":
		return name + ".test.ts"
	default: // jest
		return name + ".test.ts"
	}
}

func (g *TypeScriptGenerator) generateFile(group string, cases []TestCase, framework string) string {
	var sb strings.Builder

	// Header
	sb.WriteString("/**\n")
	sb.WriteString(" * Code generated by visionspec testgen. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf(" * Source: TPD section for %s tests\n", group))
	sb.WriteString(" */\n\n")

	// Generate describe block
	describeTitle := g.formatGroupTitle(group)
	sb.WriteString(fmt.Sprintf("describe('%s', () => {\n", describeTitle))

	// Generate test cases
	for _, tc := range cases {
		sb.WriteString(g.generateTestCase(tc, framework))
	}

	sb.WriteString("});\n")

	return sb.String()
}

func (g *TypeScriptGenerator) formatGroupTitle(group string) string {
	// Convert to Title Case
	words := strings.Split(group, "_")
	for i, word := range words {
		if len(word) > 0 {
			words[i] = strings.ToUpper(string(word[0])) + strings.ToLower(word[1:])
		}
	}
	return strings.Join(words, " ") + " Tests"
}

func (g *TypeScriptGenerator) generateTestCase(tc TestCase, _ string) string {
	var sb strings.Builder

	testTitle := g.makeTestTitle(tc)

	// Nested describe for grouped tests
	if tc.Type == TestTypeAPI {
		sb.WriteString(g.generateAPITest(tc, testTitle))
	} else if tc.Type == TestTypeE2E {
		sb.WriteString(g.generateE2ETest(tc, testTitle))
	} else {
		sb.WriteString(g.generateFunctionalTest(tc, testTitle))
	}

	return sb.String()
}

func (g *TypeScriptGenerator) makeTestTitle(tc TestCase) string {
	title := tc.Title
	if tc.ID != "" {
		title = fmt.Sprintf("[%s] %s", tc.ID, title)
	}
	return title
}

func (g *TypeScriptGenerator) generateFunctionalTest(tc TestCase, title string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("  test('%s', async () => {\n", escapeString(title)))

	// Priority comment
	if tc.Priority != "" {
		sb.WriteString(fmt.Sprintf("    // Priority: %s\n", tc.Priority))
	}

	// Source reference
	if tc.SourceRef != "" {
		sb.WriteString(fmt.Sprintf("    // Source: %s\n", tc.SourceRef))
	}

	sb.WriteString("\n")

	// Setup
	sb.WriteString("    // TODO: Setup\n")
	if tc.Input != "" {
		sb.WriteString(fmt.Sprintf("    // Input: %s\n", tc.Input))
	}
	sb.WriteString("\n")

	// Steps
	if len(tc.Steps) > 0 {
		sb.WriteString("    // Steps:\n")
		for i, step := range tc.Steps {
			sb.WriteString(fmt.Sprintf("    // %d. %s\n", i+1, step))
		}
		sb.WriteString("\n")
	}

	// Execute
	sb.WriteString("    // TODO: Execute test\n")
	sb.WriteString("    const result = undefined;\n\n")

	// Verify
	sb.WriteString("    // TODO: Verify\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("    // Expected: %s\n", tc.Expected))
	}
	sb.WriteString("    // expect(result).toBe(expected);\n\n")

	// Placeholder
	sb.WriteString("    expect(true).toBe(false); // TODO: Implement test\n")

	sb.WriteString("  });\n\n")

	return sb.String()
}

func (g *TypeScriptGenerator) generateAPITest(tc TestCase, title string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("  test('%s', async () => {\n", escapeString(title)))

	// Priority comment
	if tc.Priority != "" {
		sb.WriteString(fmt.Sprintf("    // Priority: %s\n", tc.Priority))
	}
	sb.WriteString("\n")

	// API test structure
	sb.WriteString("    // TODO: Setup API client\n")
	sb.WriteString("    // const client = new ApiClient();\n\n")

	// Input
	if tc.Input != "" {
		sb.WriteString(fmt.Sprintf("    // Request: %s\n", tc.Input))
	}

	sb.WriteString("    // TODO: Make API call\n")
	sb.WriteString("    // const response = await client.request(...);\n\n")

	// Verify
	sb.WriteString("    // TODO: Verify response\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("    // Expected: %s\n", tc.Expected))
	}
	sb.WriteString("    // expect(response.status).toBe(200);\n")
	sb.WriteString("    // expect(response.body).toMatchObject({...});\n\n")

	// Placeholder
	sb.WriteString("    expect(true).toBe(false); // TODO: Implement test\n")

	sb.WriteString("  });\n\n")

	return sb.String()
}

func (g *TypeScriptGenerator) generateE2ETest(tc TestCase, title string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("  test('%s', async () => {\n", escapeString(title)))

	// Priority comment
	if tc.Priority != "" {
		sb.WriteString(fmt.Sprintf("    // Priority: %s\n", tc.Priority))
	}
	sb.WriteString("\n")

	// E2E test structure
	sb.WriteString("    // TODO: Setup browser/page\n")
	sb.WriteString("    // const page = await browser.newPage();\n\n")

	// Steps
	if len(tc.Steps) > 0 {
		sb.WriteString("    // User Journey Steps:\n")
		for i, step := range tc.Steps {
			sb.WriteString(fmt.Sprintf("    // Step %d: %s\n", i+1, step))
		}
		sb.WriteString("\n")
	}

	// Execute steps
	sb.WriteString("    // TODO: Execute journey steps\n")
	sb.WriteString("    // await page.goto('/');\n")
	sb.WriteString("    // await page.click('button');\n\n")

	// Verify
	sb.WriteString("    // TODO: Verify journey outcome\n")
	if tc.Expected != "" {
		sb.WriteString(fmt.Sprintf("    // Assertions: %s\n", tc.Expected))
	}
	sb.WriteString("    // await expect(page.locator('...')).toBeVisible();\n\n")

	// Placeholder
	sb.WriteString("    expect(true).toBe(false); // TODO: Implement test\n")

	sb.WriteString("  });\n\n")

	return sb.String()
}

// escapeString escapes special characters for use in JavaScript strings.
func escapeString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	return s
}
