// Package diagram generates workflow visualizations from profiles.
//
// Supports generating D2 and Mermaid diagram source code from
// profile synthesis rules and workflow definitions.
package diagram

import (
	"fmt"
	"strings"

	"github.com/ProductBuildersHQ/specification-workflow-spec/pkg/synthesis"
	"github.com/ProductBuildersHQ/specification-workflow-spec/pkg/workflow"
)

// Format specifies the output diagram format.
type Format string

const (
	// FormatD2 generates D2 diagram language.
	FormatD2 Format = "d2"

	// FormatMermaid generates Mermaid diagram language.
	FormatMermaid Format = "mermaid"
)

// Options configures diagram generation.
type Options struct {
	// Title is the diagram title.
	Title string

	// Direction is the flow direction (down, right, left, up).
	Direction string

	// ShowLegend includes a legend in the diagram.
	ShowLegend bool

	// IncludeOptional includes optional specs in the diagram.
	IncludeOptional bool
}

// DefaultOptions returns sensible defaults for diagram generation.
func DefaultOptions() Options {
	return Options{
		Direction:       "down",
		ShowLegend:      true,
		IncludeOptional: false,
	}
}

// Generate creates a diagram from a profile in the specified format.
func Generate(p *workflow.Workflow, format Format, opts Options) (string, error) {
	if opts.Title == "" {
		opts.Title = p.Name + " Workflow"
	}

	switch format {
	case FormatD2:
		return generateD2(p, opts), nil
	case FormatMermaid:
		return generateMermaid(p, opts), nil
	default:
		return "", fmt.Errorf("unsupported format: %s", format)
	}
}

// generateD2 creates a D2 diagram from the profile.
func generateD2(p *workflow.Workflow, opts Options) string {
	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "# %s\n", opts.Title)
	b.WriteString("# Generated by specification-workflow-spec\n\n")
	fmt.Fprintf(&b, "direction: %s\n\n", opts.Direction)

	// Title
	b.WriteString("title: {\n")
	fmt.Fprintf(&b, "  label: %s\n", opts.Title)
	b.WriteString("  near: top-center\n")
	b.WriteString("  shape: text\n")
	b.WriteString("  style.font-size: 24\n")
	b.WriteString("  style.bold: true\n")
	b.WriteString("}\n\n")

	// Collect specs and their properties
	specs := collectSpecs(p, opts.IncludeOptional)

	// Generate nodes
	for _, spec := range specs {
		b.WriteString(generateD2Node(spec))
	}
	b.WriteString("\n")

	// Generate edges from synthesis rules
	if p.Synthesis != nil {
		for target, rule := range p.Synthesis {
			for _, source := range rule.Sources {
				// Check if both source and target are in our spec list
				if containsSpec(specs, source) && containsSpec(specs, target) {
					fmt.Fprintf(&b, "%s -> %s: synthesize\n", source, target)
				}
			}
		}
	}

	// Legend
	if opts.ShowLegend {
		b.WriteString("\n")
		b.WriteString(generateD2Legend())
	}

	return b.String()
}

// generateMermaid creates a Mermaid diagram from the profile.
func generateMermaid(p *workflow.Workflow, opts Options) string {
	var b strings.Builder

	// Header
	direction := "TB"
	if opts.Direction == "right" {
		direction = "LR"
	}
	fmt.Fprintf(&b, "flowchart %s\n", direction)

	// Collect specs
	specs := collectSpecs(p, opts.IncludeOptional)

	// Generate nodes with styling
	for _, spec := range specs {
		b.WriteString(generateMermaidNode(spec))
	}
	b.WriteString("\n")

	// Generate edges from synthesis rules
	if p.Synthesis != nil {
		for target, rule := range p.Synthesis {
			for _, source := range rule.Sources {
				if containsSpec(specs, source) && containsSpec(specs, target) {
					fmt.Fprintf(&b, "    %s -->|synthesize| %s\n", source, target)
				}
			}
		}
	}

	// Styling
	b.WriteString("\n")
	b.WriteString(generateMermaidStyles(specs))

	return b.String()
}

// SpecInfo holds information about a spec for diagram generation.
type SpecInfo struct {
	ID          string
	Label       string
	Category    string
	Required    bool
	Synthesized bool
}

// collectSpecs gathers spec information from the profile.
func collectSpecs(p *workflow.Workflow, includeOptional bool) []SpecInfo {
	var specs []SpecInfo

	if p.SpecConfig == nil {
		return specs
	}

	for id, req := range p.SpecConfig {
		if !includeOptional && !req.Required {
			continue
		}

		category := req.Category
		if category == "" {
			category = "source"
		}

		// Determine if this spec is synthesized
		synthesized := false
		if p.Synthesis != nil {
			if _, ok := p.Synthesis[id]; ok {
				synthesized = true
			}
		}

		specs = append(specs, SpecInfo{
			ID:          id,
			Label:       formatLabel(id),
			Category:    category,
			Required:    req.Required,
			Synthesized: synthesized,
		})
	}

	return specs
}

// formatLabel converts a spec ID to a display label.
func formatLabel(id string) string {
	labels := map[string]string{
		"mrd":              "MRD\\n(Market Requirements)",
		"prd":              "PRD\\n(Product Requirements)",
		"uxd":              "UXD\\n(User Experience)",
		"opportunity-spec": "OpportunitySpec\\n(12-Box Canvas)",
		"press":            "Press Release\\n(Vision Document)",
		"faq":              "FAQ\\n(Challenge Assumptions)",
		"narrative-6p":     "6-Pager Narrative\\n(Executive Document)",
		"narrative-1p":     "1-Pager\\n(Executive Summary)",
		"trd":              "TRD\\n(Technical Design)",
		"tpd":              "TPD\\n(Test Plan)",
		"ird":              "IRD\\n(Infrastructure)",
		"plan":             "PLAN\\n(Implementation)",
		"roadmap":          "ROADMAP\\n(Tracking)",
		"bmc":              "BMC\\n(Business Model)",
		"hypothesis":       "Hypothesis\\n(Core Assumption)",
		"shapeup-pitch":    "Pitch\\n(Shape Up)",
		"ost":              "OST\\n(Opportunity Tree)",
	}

	if label, ok := labels[id]; ok {
		return label
	}
	return strings.ToUpper(id)
}

// generateD2Node creates a D2 node definition.
func generateD2Node(spec SpecInfo) string {
	var b strings.Builder

	fill, stroke := categoryColors(spec.Category)

	fmt.Fprintf(&b, "%s: {\n", spec.ID)
	fmt.Fprintf(&b, "  label: %s\n", spec.Label)
	b.WriteString("  shape: rectangle\n")
	fmt.Fprintf(&b, "  style.fill: \"%s\"\n", fill)
	fmt.Fprintf(&b, "  style.stroke: \"%s\"\n", stroke)
	if !spec.Required {
		b.WriteString("  style.stroke-dash: 3\n")
	}
	b.WriteString("}\n\n")

	return b.String()
}

// generateMermaidNode creates a Mermaid node definition.
func generateMermaidNode(spec SpecInfo) string {
	label := strings.ReplaceAll(spec.Label, "\\n", "<br/>")
	return fmt.Sprintf("    %s[\"%s\"]\n", spec.ID, label)
}

// generateD2Legend creates a D2 legend.
func generateD2Legend() string {
	return `legend: {
  label: Legend
  near: bottom-center
  grid-columns: 4

  human: {
    label: Human-Authored
    shape: rectangle
    style.fill: "#e8f5e9"
    style.stroke: "#2e7d32"
  }

  synth: {
    label: Synthesized
    shape: rectangle
    style.fill: "#e3f2fd"
    style.stroke: "#1565c0"
  }

  hybrid: {
    label: Hybrid
    shape: rectangle
    style.fill: "#fff3e0"
    style.stroke: "#ef6c00"
  }

  exec: {
    label: Executive
    shape: rectangle
    style.fill: "#fce4ec"
    style.stroke: "#c2185b"
  }
}
`
}

// generateMermaidStyles creates Mermaid style definitions.
func generateMermaidStyles(specs []SpecInfo) string {
	var b strings.Builder

	// Group specs by category
	source := []string{}
	gtm := []string{}
	technical := []string{}
	execution := []string{}

	for _, spec := range specs {
		switch spec.Category {
		case "source":
			source = append(source, spec.ID)
		case "gtm":
			gtm = append(gtm, spec.ID)
		case "technical":
			technical = append(technical, spec.ID)
		case "execution", "output":
			execution = append(execution, spec.ID)
		}
	}

	if len(source) > 0 {
		b.WriteString("    classDef source fill:#e8f5e9,stroke:#2e7d32\n")
		fmt.Fprintf(&b, "    class %s source\n", strings.Join(source, ","))
	}
	if len(gtm) > 0 {
		b.WriteString("    classDef gtm fill:#e3f2fd,stroke:#1565c0\n")
		fmt.Fprintf(&b, "    class %s gtm\n", strings.Join(gtm, ","))
	}
	if len(technical) > 0 {
		b.WriteString("    classDef technical fill:#fff3e0,stroke:#ef6c00\n")
		fmt.Fprintf(&b, "    class %s technical\n", strings.Join(technical, ","))
	}
	if len(execution) > 0 {
		b.WriteString("    classDef execution fill:#fce4ec,stroke:#c2185b\n")
		fmt.Fprintf(&b, "    class %s execution\n", strings.Join(execution, ","))
	}

	return b.String()
}

// categoryColors returns fill and stroke colors for a category.
func categoryColors(category string) (fill, stroke string) {
	switch category {
	case "source":
		return "#e8f5e9", "#2e7d32" // Green
	case "gtm":
		return "#e3f2fd", "#1565c0" // Blue
	case "technical":
		return "#fff3e0", "#ef6c00" // Orange
	case "execution", "output":
		return "#fce4ec", "#c2185b" // Pink
	default:
		return "#f5f5f5", "#616161" // Gray
	}
}

// containsSpec checks if a spec ID is in the list.
func containsSpec(specs []SpecInfo, id string) bool {
	for _, s := range specs {
		if s.ID == id {
			return true
		}
	}
	return false
}

// GenerateFromDAG creates a diagram directly from a synthesis DAG.
func GenerateFromDAG(dag *synthesis.DAG, format Format, title string) (string, error) {
	switch format {
	case FormatD2:
		return generateD2FromDAG(dag, title), nil
	case FormatMermaid:
		return generateMermaidFromDAG(dag, title), nil
	default:
		return "", fmt.Errorf("unsupported format: %s", format)
	}
}

func generateD2FromDAG(dag *synthesis.DAG, title string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", title)
	b.WriteString("direction: down\n\n")

	// Nodes
	for _, node := range dag.Nodes {
		fmt.Fprintf(&b, "%s: %s\n", node, formatLabel(node))
	}
	b.WriteString("\n")

	// Edges
	for _, edge := range dag.Edges {
		fmt.Fprintf(&b, "%s -> %s\n", edge.Source, edge.Target)
	}

	return b.String()
}

func generateMermaidFromDAG(dag *synthesis.DAG, _ string) string {
	var b strings.Builder

	b.WriteString("flowchart TB\n")

	// Nodes
	for _, node := range dag.Nodes {
		label := strings.ReplaceAll(formatLabel(node), "\\n", "<br/>")
		fmt.Fprintf(&b, "    %s[\"%s\"]\n", node, label)
	}
	b.WriteString("\n")

	// Edges
	for _, edge := range dag.Edges {
		fmt.Fprintf(&b, "    %s --> %s\n", edge.Source, edge.Target)
	}

	return b.String()
}
